### ISSUE TITLE
Please remove "campaign_term"

### ISSUE THREAD

**Issue by alexj** [activeprospect/leadconduit-fields#119]
We added `campaign_term`, but it overlaps heavily with `search_term`, which will likely cause confusion. Can we do a quick check to see if it's in use anywhere (I doubt it)? If no one is using it, please delete it outright. Otherwise, we should mark it as depracated, recommending the use of `search_term`.

**Comment by alexj** [comment]
Fixed via the Superadmin feature, though it threw an error. Justin is following up on it.

**Comment by richvida** [comment]
This decision makes no sense. Please add it back.

**Comment by alexkwolfe** [comment]
Hi @richvida, can you tell us more about why `search_term` isn't working for you?
