### ISSUE TITLE
Website fields (and other URLs) should prepend the protocol when missing

### ISSUE THREAD

**Issue by alexj** [activeprospect/leadconduit-fields#123]
In the cases where a URL doesn't include `http://` or `https://`LeadConduit marks the value as invalid. Can we change this behavior to either accept protocol-less URLs or have it auto-prepend `http://`?

**Comment by alexkwolfe** [comment]
Yes. I think we could do that. This is an issue for the leadconduit-types repo. I'll open an issue there.
