### ISSUE TITLE
Add timing to the mortgage integration

### ISSUE THREAD

**Issue by kcaponeAP** [activeprospect/leadconduit-fields#15]
Please add mortgage.application.timing to the mortgage integration. Adding this here so it can be made available for the military.com integration.

Type: Range
Potential Values: 
2 = Presently
3 = 2-3 Months
4 = 3-6 Months

**Comment by alexkwolfe** [comment]
@kacaponeAP, is this still an issue?

**Comment by alexj** [comment]
@kcaponeAP can we close this, or is it still an issue?

**Comment by kcaponeAP** [comment]
it hasn't come up recently closing for now.
