### ISSUE TITLE
Incorrect deprecated field name for mortgage.application.bankruptcy

### ISSUE THREAD

**Issue by alexkwolfe** [activeprospect/leadconduit-fields#32]
The `mortgage.application.bankruptcy` field should be deprecated in favor of `mortgage.bankruptcy.was_declared` rather than `mortgage.bankruptcy.was_discharged`.

![pastedgraphic-3](https://cloud.githubusercontent.com/assets/569/6189513/d1a59f4e-b360-11e4-8698-8f2fadc4dbb2.png)

**Comment by cgrayson** [comment]
Fixed in 2.0.1
