### ISSUE TITLE
rename 'company.' fields

### ISSUE THREAD

**Issue by cgrayson** [activeprospect/leadconduit-fields#34]
Ten new standard fields have been added, for use by the [Lendio integration](https://github.com/activeprospect/leadconduit-integration-lendio/). They were unfortunately named in a way similar to the pre-existing field `company` (for "Company Name"), and there is now a conflict between `company` the string and `company` the collection of other company attributes (e.g., `company.time_in_business`).

Because `company` is already in use in several production integrations (e.g., BuyerZone, LendingTree, Mortech, & Velocify), I think that rather than change it to `company.name`, it would be easier to change these other new attributes' prefix, which are currently used in zero production integrations. 

The best prefix I can think of is `business.`. 

I also wonder if the following fields can be removed entirely, as they are either not used or don't need to be used, even by the Lendio integration: 

* `company.address_1`
* `company.city`
* `company.state`
* `company.postal_code`

**Comment by alexkwolfe** [comment]
It looks like some of those fields are used by the Lendio integration:

https://github.com/activeprospect/leadconduit-integration-lendio/blob/c5055b715281735d42da64b6fbe82bd0bbd976df/src/outbound.coffee#L32-L34

**Comment by cgrayson** [comment]
> It looks like some of those fields are used by the Lendio integration:

That's right, but I don't see why they are, versus regular ol' `address_1` and `city`.

**Comment by zalary** [comment]
I wrote the specs for this, so I'll say what I did it that way, which was

You have an individual's name, but the address and city is of their business, not their person and they are applying for a business loan. Having an employer/business address tied to an individual seemed strange (even if that tie was implied and not explicit)

**Comment by alexkwolfe** [comment]
IMO, the company's attributes should have consistent names, even if it means a headache in the short-term. I'm not a fan of having a field called `company` (for the name of the business) and a field called `business.address_1` for the address of that business because I feel that it will unnecessarily confound sources who post leads and users who configure rules and mappings. 

The purpose of marking a field deprecated is to help ease the transition involved in renaming a field. If that mechanism is insufficient, then I propose devising one that works better. This is a problem we are going to continue to face as the set of fields grows. So it's worth using this opportunity to refine the process for renaming standard fields.

**Comment by zalary** [comment]
could there be an easier change, which would be to change/deprecate the company string to map to business.name? or is there a strong preference for company as the overarching object/naming convention?

**Comment by ros3bud** [comment]
Looks like I should have used company.postal_code to pass to the lendio var business_zip, but I used lead.postal_code.

**Comment by zalary** [comment]
in this case, it seems like deprecation isn't actually deprecation the way we've been doing it where we would have some leeway to make changes.  if we stick with the company object and deprecate company as a string, we're going to have make the changes to all the integrations currently using the company string before Lendio can go live, is that true?

**Comment by cgrayson** [comment]
> The purpose of marking a field deprecated is to help ease the transition involved in renaming a field. If that mechanism is insufficient, then I propose devising one that works better. This is a problem we are going to continue to face as the set of fields grows. So it's worth using this opportunity to refine the process for renaming standard fields.

Marking something as deprecated couldn't be easier. And if we take the Java™ approach to deprecating things, i.e., never really remove them, then no hardship ensues. 

Anyway, I guess I'm unclear on what the full "mechanism" and "process" involves. It seemed like this trouble with `company` was going to be blocking completion of the Lendio integration, but I guess that was misunderstanding on my part.

**Comment by alexkwolfe** [comment]
The full mechanism and process is not well defined. Now is an opportunity to figure out how it should work and make it so.

**Comment by ros3bud** [comment]
The trouble with company is actually blocking completion of the Lendio integration. Business_name is a required field, so we need a way to pass it.

**Comment by alexkwolfe** [comment]
So if we added a new field called `company.name` and deprecated `company`, then I think we've solved the problem in the short term, haven't we?

**Comment by cgrayson** [comment]
Yes.

**Comment by ros3bud** [comment]
Yes indeed.

**Comment by alexkwolfe** [comment]
So I guess I don't see how this is a blocker.

**Comment by ros3bud** [comment]
From what we talked about Friday, my understanding of why this was a blocker is because it brings up the larger issue of how to replace any use of company with company.name.

**Comment by alexkwolfe** [comment]
Yes. It does bring that question up. But it's still not a blocker.

**Comment by ros3bud** [comment]
I could move forward using the standard fields which are available, however that would mean passing lead.company.company to the business_name.

**Comment by alexkwolfe** [comment]
Why would you choose to do that rather than add a new field called `company.name` and deprecate `company`?

**Comment by ros3bud** [comment]
Because there are several other integrations which are using company.

**Comment by alexkwolfe** [comment]
https://github.com/activeprospect/docs.leadconduit.com/issues/11
