### ISSUE TITLE
Add lowermybills.additional_info

### ISSUE THREAD

**Issue by alexkwolfe** [activeprospect/leadconduit-fields#36]
The type should be `string`.

This field is a dependency of the LMB inbound integration [issue #18](https://github.com/activeprospect/leadconduit-integration-lowermybills/issues/18#issuecomment-92467919).

**Comment by zalary** [comment]
I can take this on and probably get it knocked out shortly #famouslastwords

**Comment by cgrayson** [comment]
Turns out that this [already existed](https://github.com/activeprospect/leadconduit-fields/blame/master/fields/lowermybills.json).
