### ISSUE TITLE
Please add Lead ID to docs.leadconduit.com

### ISSUE THREAD

**Issue by kcaponeAP** [activeprospect/leadconduit-fields#37]
This is regarding lead id, which is the AP identifier for leads. Is there a way to add this to the fields section so that it's available for customers to use?

http://docs.leadconduit.com/fields

**Comment by cgrayson** [comment]
I opened an issue on the docs repo to show this. But I think it's already shown in the UI wherever it can be used, e.g., in mappings dropdowns. Is it missing from somewhere where you'd expect to see it?

**Comment by kcaponeAP** [comment]
It's just missing from the docs.leadconduit.com site.
