### ISSUE TITLE
time_to_contact is duplicated

### ISSUE THREAD

**Issue by ros3bud** [activeprospect/leadconduit-fields#39]
Here: 
https://github.com/activeprospect/leadconduit-fields/blob/c51bbb14dff7b869f74b77452cfba5b79a774ee9/fields/contact.json#L16

And here: 
https://github.com/activeprospect/leadconduit-fields/blob/395ca2a8378b07fb7143d28ad3b619594601a48a/fields/personal.json#L4

**Comment by alexkwolfe** [comment]
Aren't those the same line?

**Comment by ros3bud** [comment]
updated.

**Comment by cgrayson** [comment]
Lynda - Jonathan noticed this issue again while working on #48; we wondered why you closed this?

**Comment by ros3bud** [comment]
Thanks for catching. I must have mistakenly thought this was solved.
