### ISSUE TITLE
time_to_contact does not entirely encompass the data leadpoint needs to pass

### ISSUE THREAD

**Issue by ros3bud** [activeprospect/leadconduit-fields#40]
At the moment, it seems like the best field for values such as morning_primary, morning_secondary, afternoon_primary, afternoon_secondary etc is indeed time_to_contact. 

However, this is problematic because when LP sends this data they are referring to the time and phone number a person would most like to be contacted at. It causes two pieces of data to be added to the one field. It also extends the definition of time_to_contact into new territory. 

Should we create a new internal field for this data? Thoughts and feedback welcome.

**Comment by ros3bud** [comment]
@alexkwolfe, @cgrayson, @zalary ^ ^

**Comment by zalary** [comment]
what data DOES Leadpoint pass or want to pass into this field?

**Comment by ros3bud** [comment]
morning_primary, morning_secondar, afternoon_primary, afternoon_secondary, evening_primary, evening_secondary.

**Comment by zalary** [comment]
I would probably recommend creating a new field to encompass this.

barring that, I would create a new time_to_contact_secondary and maybe update the description of the original time_to_contact field to indicate it's meant for primary)

I don't know, it's all very subjective, so do what feels right, providing @alexkwolfe approves :grinning:

**Comment by alexkwolfe** [comment]
Do they provide multiple values, or just one?

**Comment by ros3bud** [comment]
Just one. I'm starting to wonder if maybe we can just parse this better, too. Example soon to follow.

**Comment by alexkwolfe** [comment]
Maybe we can place the preferred phone in phone_1 and set the time_to_contact to "morning" or whatever.

**Comment by ros3bud** [comment]
Right - we can parse out morning, afternoon or evening into time_to_contact and LP is already sending primary and secondary phone. This makes morning_primary somewhat redundant.

**Comment by ros3bud** [comment]
Updated Leadpoint to account for this issue in version 1.6.2.
