### ISSUE TITLE
Add num_buyers field

### ISSUE THREAD

**Issue by alexkwolfe** [activeprospect/leadconduit-fields#62]
ID: `num_buyers`
Type: `range`
Description: `"Number of expected buyers of this lead (1 or more)"`
Examples: `"1", "1+", "1-5"`

**Comment by alexkwolfe** [comment]
LGTM :rocket:

**Comment by cgrayson** [comment]
I bet you meant that for the PR, eh?

**Comment by alexkwolfe** [comment]
Sonova.
