### ISSUE TITLE
Filters are missing some Briteverify fields

### ISSUE THREAD

**Issue by alexj** [activeprospect/leadconduit-fields#68]
Karalyn is working on some changes and discovered that the field she needs for a filter isn't included. Please add `BriteVerify Email Connected` to the options in the filter drop-down. This field is returned by the integration.

**Comment by alexkwolfe** [comment]
I filed [this issue in the integration repo](https://github.com/activeprospect/leadconduit-integration-briteverify/issues/14), instead.
