### ISSUE TITLE
loan.amount is not resolving to a range. 

### ISSUE THREAD

**Issue by ros3bud** [activeprospect/leadconduit-fields#72]
It's unclear whether this is relevant, but the spacing for the examples is different for loan.amount and loan.timeframe_days. I point this out because loan.timeframe_days is working.

**Comment by alexkwolfe** [comment]
Can you provide an example?

**Comment by ros3bud** [comment]
It's a strange example, but if you take a look at my branch in the Lendio repo inbound-lw-2 - I updated the test so that only the test about finance_amount is being ran. 

it.only 'should parse finance_amount', ->
      assert.equal body.finance_amount, '107'

When I console logged the results of value from the inRange (line 194) method, value does not have a max and min.

**Comment by alexkwolfe** [comment]
This is a problem with your test. Let me know if you can't find it.
