### ISSUE TITLE
phone type's valueOf/normal should include extension

### ISSUE THREAD

**Issue by cgrayson** [activeprospect/leadconduit-fields#85]
In [this Slack conversation](https://activeprospect.slack.com/archives/leadconduit/p1453754954000191), it was determined that the "normal" value for `phone`-type fields doesn't include the extension. Seems like it should. 

Thoughts, @alexkwolfe?

**Comment by alexkwolfe** [comment]
Duplicate? https://github.com/activeprospect/leadconduit-types/issues/24

**Comment by cgrayson** [comment]
Yes. And on the wrong repo, too. #derp
