### ISSUE TITLE
Add Two Fields: Roof Type & Property Type

### ISSUE THREAD

**Issue by alexj** [activeprospect/leadconduit-fields#87]
**Name:** Property Type 
**Param:** `property.type`
**Description:** The type of property, for example: single family, multi family, condo, town home, coop, or mobile home 
_(internal note, this is intentionally different from `mortgage.property.type`, which will remain as well)_

**Name:** Roof Type
**Param:** `property.roof_type`
**Description:** The type of roof, for example: tile, shake shingle, flat, gable, cross-gabled or cross hipped

**Comment by jgrayson676** [comment]
fixed in #88
